distro: bionic
arch: arm64
language: java
jdk: openjdk11
env: HADOOP_PROFILE=default TEST_CODECS=gzip,snappy,uncompressed

before_install:
  - lscpu
  - bash dev/travis-before_install.sh
    
install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq maven
  - mvn install --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true | pv -fbi 60 > mvn_install.log || (cat mvn_install.log && false)

before_script: 
  - java -version
  - mvn -version
  
script: mvn verify --batch-mode javadoc:javadoc -P travis,$HADOOP_PROFILE
