distro: bionic
arch: arm64
language: java
jdk: openjdk11
env: HADOOP_PROFILE=default TEST_CODECS=gzip,snappy,uncompressed

cache:
  directories:
  - $HOME/.m2

before_install:
  - lscpu
  #- bash dev/travis-before_install.sh
  - export JDK_BIN=$(dirname $(which java))   # for javadoc
  - echo "JDK_BIN=$JDK_BIN"
  - ls -la $JDK_BIN
  - which javadoc
  - env
  - exit 1
  - export PATH="$JDK_BIN:$PATH"
    
install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq maven
  - java -version
  - mvn -version
  - mvn install --batch-mode -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true | pv -fbi 60 > mvn_install.log || (cat mvn_install.log && false)
  
script: mvn verify --batch-mode javadoc:javadoc -P travis,$HADOOP_PROFILE
